//
//  GameData.swift
//  Elden Ring Tracker
//
//  Created by Enzo Maruffa on 13/03/22.
//

import Foundation

class StaticGameData: Codable {
    
    static var data = [
        StaticLocation(name: "Ainsel River",
                       goldenSeedCount: 2,
                       sacredTearsCount: 0,
                       crystalTearsCount: 0,
                       dragonHeartsCount: 0,
                       bosses: [
                        StaticBoss(id: 89, name: "Astel, Naturalborn of the Void", category: "Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167488"),
                        StaticBoss(id: 150, name: "Baleful Shadow", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168633"),
                        StaticBoss(id: 142, name: "Dragonkin Soldier", category: "Boss", detailedLocation: "Found dormant in the middle of the Lake of Rot.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168515"),
                        StaticBoss(id: 173, name: "Dragonkin Soldier of Nokstella", category: "Great Boss", detailedLocation: "Frozen Lightning Spear  Incantation", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167625"),
                        StaticBoss(id: 197, name: "Baleful Shadow", category: "Invasion", detailedLocation: "Ainsel River Main  site of grace (by resting at the Ainsel River Main site) and it will tell to kill this enemy.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168546")
                       ]),
        
        StaticLocation(name: "Altus Plateau",
                       goldenSeedCount: 15,
                       sacredTearsCount: 2,
                       crystalTearsCount: 8,
                       dragonHeartsCount: 2,
                       bosses: [
                        StaticBoss(id: 95, name: "2 x Tree Sentinels", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167584"),
                        StaticBoss(id: 141, name: "Abductor Virgins x2", category: "Boss", detailedLocation: "Subterranean Inquisition Chamber", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168514"),
                        StaticBoss(id: 138, name: "Ancient Dragon Lansseax", category: "Boss", detailedLocation: "Just southwest of  Rampartside Path  site of grace on the plateau.  Only appears after defeating in  first location . May also only appear at night time here (?)", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168510"),
                        StaticBoss(id: 60, name: "Black Knife Assassin", category: "Boss", detailedLocation: "Sage's Cave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166678"),
                        StaticBoss(id: 102, name: "Black Knife Assassin", category: "Boss", detailedLocation: "Guarding the door to  Sainted Hero's Grave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167676"),
                        StaticBoss(id: 116, name: "Cristalian Spear & Cristalian Ringblade", category: "Boss", detailedLocation: "At the end of Gaol Cave. You need to use the lever to open the cells, in one of the last there is a large room with two corpses. In the right of this room hide a passage behind a wooden planck wall. The boss is bellow it.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168080"),
                        StaticBoss(id: 90, name: "Crucible Knight & Crucible Knight Ordovis", category: "Boss", detailedLocation: "Auriza Hero's Grave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167535"),
                        StaticBoss(id: 72, name: "Deathbird", category: "Boss", detailedLocation: "Only appears at night", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167182"),
                        StaticBoss(id: 92, name: "Demi Human Queen Gilika", category: "Boss", detailedLocation: "Auriza Hero's Grave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167566"),
                        StaticBoss(id: 106, name: "Demi-Human Queen Maggie", category: "Boss", detailedLocation: "Key Item  Memory Slot", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167815"),
                        StaticBoss(id: 80, name: "Demi-Human Queen Margot", category: "Boss", detailedLocation: "Volcano Cave .Jar Cannon", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167366"),
                        StaticBoss(id: 71, name: "Draconic Tree Sentinel", category: "Boss", detailedLocation: "Guarding the gate.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167180"),
                        StaticBoss(id: 77, name: "Elemer of the Briar", category: "Boss", detailedLocation: "Boss of  The Shaded Castle .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167323"),
                        StaticBoss(id: 140, name: "Erdtree Burial Watchdog", category: "Boss", detailedLocation: "Wyndham Catacombs", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168513"),
                        StaticBoss(id: 96, name: "Fallingstar Beast", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167585"),
                        StaticBoss(id: 70, name: "Fell Twin x 2", category: "Boss", detailedLocation: "Middle of the bridge.Omenkiller Rollo", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167171"),
                        StaticBoss(id: 79, name: "Full-Grown Fallingstar Beast", category: "Boss", detailedLocation: "South of  Ninth Mt. Gelmir Campsite  at the top of the mountain by ladder or air jump (?)", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167365"),
                        StaticBoss(id: 99, name: "Godefroy the Grafted", category: "Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167645"),
                        StaticBoss(id: 39, name: "Godskin Apostle", category: "Boss", detailedLocation: "At  Windmill Heights  on top of the hill", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166231"),
                        StaticBoss(id: 120, name: "Godskin Noble", category: "Boss", detailedLocation: "Temple of Eiglay", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168177"),
                        StaticBoss(id: 66, name: "Grave Warden Duelist", category: "Boss", detailedLocation: "Auriza Side TombSoldjars of Fortune Ashes", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167018"),
                        StaticBoss(id: 139, name: "Kindred Rot x 2", category: "Boss", detailedLocation: "[Seethewater Cave] Boss.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168512"),
                        StaticBoss(id: 75, name: "Lesser Black Blade Kindred", category: "Boss", detailedLocation: "Visible from the  West Capital RampartGargoyle's Halberd", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167312"),
                        StaticBoss(id: 83, name: "Magma Wyrm", category: "Boss", detailedLocation: "Just south of  Fort Laied  in the Magma pool.Dragon Heart", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167377"),
                        StaticBoss(id: 63, name: "Maleigh Marais, Shaded Castle Castellan", category: "Boss", detailedLocation: "Just West of  The Shaded Castle . Spawns with a Stone Golem.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166754"),
                        StaticBoss(id: 112, name: "Margit, The Fell Omen (Round 2)", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168001"),
                        StaticBoss(id: 137, name: "Miranda the Blighted Bloom", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168509"),
                        StaticBoss(id: 153, name: "Miranda, the Blighted Bloom", category: "Boss", detailedLocation: "Perfumer's Grotto", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=169017"),
                        StaticBoss(id: 59, name: "Necromancer Garris", category: "Boss", detailedLocation: "Sage's Cave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166675"),
                        StaticBoss(id: 107, name: "Night's Cavalry", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167893"),
                        StaticBoss(id: 145, name: "Night's Cavalry", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168519"),
                        StaticBoss(id: 136, name: "Omenkiller", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168508"),
                        StaticBoss(id: 152, name: "Omenkiller", category: "Boss", detailedLocation: "Perfumer's Ruins", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168973"),
                        StaticBoss(id: 154, name: "Omenkiller", category: "Boss", detailedLocation: "Volcano Manor , between the  Guest Hall  and the  Prison Town Church .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=169036"),
                        StaticBoss(id: 118, name: "Onyx Lord", category: "Boss", detailedLocation: "Sealed Tunnel", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168154"),
                        StaticBoss(id: 86, name: "Perfumer Tricia & Misbegotten Warrior", category: "Boss", detailedLocation: "Unsghtly Catacombs  bosses", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167394"),
                        StaticBoss(id: 155, name: "Prelate", category: "Boss", detailedLocation: "Fort Laied", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=169063"),
                        StaticBoss(id: 117, name: "Red Wolf of the Champion", category: "Boss", detailedLocation: "Spirit Ash  Bloodhound Knight Floh", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168140"),
                        StaticBoss(id: 100, name: "Sanguine Noble", category: "Boss", detailedLocation: "Writheblood Ruins , in the underground crypt.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167656"),
                        StaticBoss(id: 135, name: "Stonedigger Troll", category: "Boss", detailedLocation: "Altus Tunnel", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168507"),
                        StaticBoss(id: 91, name: "Tibia Mariner", category: "Boss", detailedLocation: "Auriza Hero's Grave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167560"),
                        StaticBoss(id: 111, name: "Twin-Blade Gargoyle", category: "Boss", detailedLocation: "On top of the stairs; will fly in once you approach the area.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167998"),
                        StaticBoss(id: 69, name: "Ulcerated Tree Spirit", category: "Boss", detailedLocation: "Just North of  Lower Capital Church  Site of Grace in the open area.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167141"),
                        StaticBoss(id: 97, name: "Ulcerated Tree Spirit", category: "Boss", detailedLocation: "Directly South of  Outer Wall Phantom Tree  site of grace. It spawns from the center of the camp.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167586"),
                        StaticBoss(id: 105, name: "Ulcerated Tree Spirit", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167812"),
                        StaticBoss(id: 76, name: "Wormface", category: "Boss", detailedLocation: "Boss at the base of the Minor Erdtree.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167317"),
                        StaticBoss(id: 162, name: "Godfrey, First Elden Lord", category: "Demigod", detailedLocation: "At the [Erdtree Sanctuary] site of grace.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167693"),
                        StaticBoss(id: 160, name: "Morgott, the Omen King", category: "Demigod", detailedLocation: "Southeast of  Queen's Bedchamber  Site of Grace.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167374"),
                        StaticBoss(id: 161, name: "Rykard, Lord of Blasphemy", category: "Demigod", detailedLocation: "Mt. Gelmir", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167571"),
                        StaticBoss(id: 172, name: "Ancient Dragon Lansseax", category: "Great Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167545"),
                        StaticBoss(id: 175, name: "Erdtree Avatar", category: "Great Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168147"),
                        StaticBoss(id: 176, name: "Mohg, the Omen", category: "Great Boss", detailedLocation: "Found in the Subterranean Shunning-Grounds (?). Accessible from Forsaken Depths", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168657"),
                        StaticBoss(id: 184, name: "Anastasia, Tarnished-Eater", category: "Invasion", detailedLocation: "Just before  Corpse-Stench Shack .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166625"),
                        StaticBoss(id: 201, name: "Crucible Knight", category: "Invasion", detailedLocation: "Near  Tanith ; triggered by attacking her.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168972"),
                        StaticBoss(id: 204, name: "Dung Eater", category: "Invasion", detailedLocation: "In the moat, near  Leyndell, Royal Capital .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=169012"),
                        StaticBoss(id: 193, name: "Eleonora, Violet Bloody Finger", category: "Invasion", detailedLocation: "Part of Bloody Finger Hunter Yura's  quest", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168051"),
                        StaticBoss(id: 198, name: "Inquisitor Ghiza", category: "Invasion", detailedLocation: "Upstairs in  Volcano Manor", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168637"),
                        StaticBoss(id: 195, name: "Vargram, the Raging Wolf", category: "Invasion", detailedLocation: "Near  Fortified Manor, First Floor .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168423")
                       ]),
        
        StaticLocation(name: "Caelid",
                       goldenSeedCount: 4,
                       sacredTearsCount: 1,
                       crystalTearsCount: 5,
                       dragonHeartsCount: 7,
                       bosses: [StaticBoss(id: 109, name: "3 Crystalians", category: "Boss", detailedLocation: "Sellia Hidaway", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167921"),
                                StaticBoss(id: 87, name: "Battlemage Hugues", category: "Boss", detailedLocation: "Sellia EvergaolBattlemage Hugues Spirit Ashes", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167402"),
                                StaticBoss(id: 108, name: "Beastman of Farum Azula", category: "Boss", detailedLocation: "Dragonbarrow Cave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167916"),
                                StaticBoss(id: 144, name: "Cemetery Shade", category: "Boss", detailedLocation: "At the end of  Caelid Catacombs . Activate the lever hidden behind an invisible wall on the central pillar in front of the boss door.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168518"),
                                StaticBoss(id: 122, name: "Cleanrot Knight (Spear) & Cleanrot Knight (Sickle)", category: "Boss", detailedLocation: "Final Boss(es) of the  Abandoned Cave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168213"),
                                StaticBoss(id: 36, name: "Crucible Knight & Misbegotten Warrior", category: "Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166176"),
                                StaticBoss(id: 67, name: "Death Rite Bird", category: "Boss", detailedLocation: "Appears only at night.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167019"),
                                StaticBoss(id: 31, name: "Decaying Ekzykes", category: "Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165933"),
                                StaticBoss(id: 34, name: "Dragon (?)", category: "Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166017"),
                                StaticBoss(id: 51, name: "Erdtree Avatar", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166512"),
                                StaticBoss(id: 58, name: "Erdtree Burial Watchdog Duo", category: "Boss", detailedLocation: "Minor Erdtree Catacombs", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166671"),
                                StaticBoss(id: 94, name: "Fallenstar Beast", category: "Boss", detailedLocation: "Sellia Crystal Tunnel", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167582"),
                                StaticBoss(id: 115, name: "Frenzied Duelist", category: "Boss", detailedLocation: "At the end of Gaol Cave. You need to use the lever to open the cells, in one of the last there is a large room with two corpses. In the right of this room hide a passage behind a wooden planck wall. The boss is bellow it.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168033"),
                                StaticBoss(id: 57, name: "Godskin Apostle", category: "Boss", detailedLocation: "Divine Tower of Caelid", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166668"),
                                StaticBoss(id: 33, name: "Greyll", category: "Boss", detailedLocation: "On the bridgeDragon Heart", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166013"),
                                StaticBoss(id: 38, name: "Greyoll", category: "Boss", detailedLocation: "In front of Fort Faroth Site of Grace.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166189"),
                                StaticBoss(id: 61, name: "Mad Pumpkin Heads (Hammer & Flail)", category: "Boss", detailedLocation: "Caelem Ruins   - Underground", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166738"),
                                StaticBoss(id: 73, name: "Magma Wyrm", category: "Boss", detailedLocation: "Gael TunnelMoonveil Katana", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167222"),
                                StaticBoss(id: 45, name: "Night Cavalry", category: "Boss", detailedLocation: "South of Aeonia SwampAsh of War: Poison Moth Flight", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166477"),
                                StaticBoss(id: 53, name: "Night's Cavalry", category: "Boss", detailedLocation: "On the bridge. Only spawns at night.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166616"),
                                StaticBoss(id: 48, name: "Nox Swordstress & Nox Priest", category: "Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166499"),
                                StaticBoss(id: 52, name: "Putrid Avatar", category: "Boss", detailedLocation: "East of the Minor Erdtree", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166615"),
                                StaticBoss(id: 84, name: "Putrid Tree Spirit", category: "Boss", detailedLocation: "At the end of  War-Dead Catacombs", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167378"),
                                StaticBoss(id: 159, name: "Starscourge Radahn", category: "Demigod", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165444"),
                                StaticBoss(id: 170, name: "Black Blade Kindred", category: "Great Boss", detailedLocation: "Outside the  Bestial Sanctum", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166006"),
                                StaticBoss(id: 171, name: "Commander O'Neil", category: "Great Boss", detailedLocation: "On the Heart of Aeonia site of grace, the site appear after defeating him.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166073"),
                                StaticBoss(id: 192, name: "Bell Bearing Hunter", category: "Invasion", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168044"),
                                StaticBoss(id: 185, name: "Millicent", category: "Invasion", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166650")]),
        
        StaticLocation(name: "Crumbling Farum Azula",
                       goldenSeedCount: 2,
                       sacredTearsCount: 0,
                       crystalTearsCount: 0,
                       dragonHeartsCount: 0,
                       bosses: [
                        StaticBoss(id: 148, name: "Dragonlord Placidusax", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168522"),
                        StaticBoss(id: 85, name: "Godskin Duo", category: "Boss", detailedLocation: "[Dragon Temple Altar] site of grac", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167392"),
                        StaticBoss(id: 98, name: "Maliketh, the Black Blade", category: "Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167619"),
                        StaticBoss(id: 194, name: "Recusant Bernahl", category: "Invasion", detailedLocation: "Crumbling Farum Azula", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168392")
                       ]),
        
        StaticLocation(name: "Deeproot Depths",
                       goldenSeedCount: 0,
                       sacredTearsCount: 0,
                       crystalTearsCount: 0,
                       dragonHeartsCount: 0,
                       bosses: [
                        StaticBoss(id: 132, name: "Crucible Knight Siluria", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168429"),
                        StaticBoss(id: 127, name: "Crucible Knight Sirulia", category: "Boss", detailedLocation: "Deeproot Depths", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168281"),
                        StaticBoss(id: 133, name: "Erdtree Avatar", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168442"),
                        StaticBoss(id: 131, name: "Fia’s Champions", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168424"),
                        StaticBoss(id: 119, name: "Lichdragon Fortissax", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168158")
                       ]),
        
        StaticLocation(name: "Limgrave",
                       goldenSeedCount: 8,
                       sacredTearsCount: 5,
                       crystalTearsCount: 7,
                       dragonHeartsCount: 2,
                       bosses: [
                        StaticBoss(id: 24, name: "Ancient Hero of Zamor", category: "Boss", detailedLocation: "Weeping EvergaolRadagaon's Scarseal", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165411"),
                        StaticBoss(id: 6, name: "Beastman of Farum Azula", category: "Boss", detailedLocation: "Groveside Cave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164472"),
                        StaticBoss(id: 16, name: "Black Knife Assassin", category: "Boss", detailedLocation: "Deathtouched CatacombsAssassin's Crimson Dagger", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164530"),
                        StaticBoss(id: 10, name: "Bloodhound Knight Darriwil", category: "Boss", detailedLocation: "Forlorn Hound Evergaol", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164486"),
                        StaticBoss(id: 23, name: "Cemetery Shade", category: "Boss", detailedLocation: "Tombsward CatacombsLhutel The Headless", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165317"),
                        StaticBoss(id: 7, name: "Crucible Knight", category: "Boss", detailedLocation: "Stormhill Evergaol", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164476"),
                        StaticBoss(id: 26, name: "Deathbird", category: "Boss", detailedLocation: "Appears at night on top of the ruin covered in Ruin FragmentsBlue-Feathered Branchsword", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165457"),
                        StaticBoss(id: 35, name: "Deathbird", category: "Boss", detailedLocation: "Spawns at nightSacrificial Axe", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166054"),
                        StaticBoss(id: 4, name: "Demi-Human Chief (2)", category: "Boss", detailedLocation: "At the end of the  Coastal Cave  dungeon.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164457"),
                        StaticBoss(id: 21, name: "Demi-Human Queen", category: "Boss", detailedLocation: "Demi-Human Forest Ruins", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165192"),
                        StaticBoss(id: 5, name: "Erdtree Burial Watchdog", category: "Boss", detailedLocation: "Past the locked door in  Stormfoot Catacombs .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164467"),
                        StaticBoss(id: 32, name: "Erdtree Burial Watchdog (Impaler's Catacombs)", category: "Boss", detailedLocation: "Impaler's CatacombsDemi-Human Ashes", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165949"),
                        StaticBoss(id: 9, name: "Flying Dragon Agheel", category: "Boss", detailedLocation: "Dragon-Burnt Ruins", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164484"),
                        StaticBoss(id: 2, name: "Grafted Scion", category: "Boss", detailedLocation: "In the prologue area", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164433"),
                        StaticBoss(id: 13, name: "Grave Warden Duelist", category: "Boss", detailedLocation: "Murkwater Catacombs", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164499"),
                        StaticBoss(id: 15, name: "Guardian Golem", category: "Boss", detailedLocation: "Highroad Cave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164509"),
                        StaticBoss(id: 18, name: "Leonine Misbegotten", category: "Boss", detailedLocation: "Castle Morne  - At the very rear in the graveyard at sea-level.Grafted Blade Greatsword", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164812"),
                        StaticBoss(id: 12, name: "Mad Pumpkin Head", category: "Boss", detailedLocation: "Underneath  Waypoint Ruins .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164490"),
                        StaticBoss(id: 30, name: "Miranda the Blighted Bloom", category: "Boss", detailedLocation: "Tombsward CaveViridian Amber Medallion", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165743"),
                        StaticBoss(id: 11, name: "Night's Cavalry", category: "Boss", detailedLocation: "Patrols the bridge between  Agheel Lake North  and  Waypoint Ruins . Only appears at night.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164488"),
                        StaticBoss(id: 17, name: "Night's Cavalry (Weeping Peninsula)", category: "Boss", detailedLocation: "Weeping Peninsula. Only appears at night.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164659"),
                        StaticBoss(id: 14, name: "Patches", category: "Boss", detailedLocation: "Murkwater Cave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164504"),
                        StaticBoss(id: 20, name: "Root Monster", category: "Boss", detailedLocation: "Underground Crypt", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165164"),
                        StaticBoss(id: 27, name: "Runebear", category: "Boss", detailedLocation: "Earthbore CaveSpelldrake Talisman", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165462"),
                        StaticBoss(id: 25, name: "Scaly Misbegotten", category: "Boss", detailedLocation: "Morne TunnelRusted Anchor", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165453"),
                        StaticBoss(id: 1, name: "Soldier of Godrick", category: "Boss", detailedLocation: "At the end of the Cave of Knowledge dungeon, within the  Stranded Graveyard .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164420"),
                        StaticBoss(id: 8, name: "Stonedigger Troll", category: "Boss", detailedLocation: "Limgrave Tunnels", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164478"),
                        StaticBoss(id: 19, name: "Tibia Mariner", category: "Boss", detailedLocation: "Summonwater Village", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164859"),
                        StaticBoss(id: 3, name: "Tree Sentinel", category: "Boss", detailedLocation: "Patrolling between the  Church of Elleh  and  The First Step .Golden Halberd", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164444"),
                        StaticBoss(id: 0, name: "Ulcerated Tree Spirit", category: "Boss", detailedLocation: "Fringefolk Hero's Grave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164143"),
                        StaticBoss(id: 157, name: "Godrick the Grafted", category: "Demigod", detailedLocation: "Stormveil Castle", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164421"),
                        StaticBoss(id: 165, name: "Erdtree Avatar", category: "Great Boss", detailedLocation: "Weeping Peninsula Erdtree", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165321"),
                        StaticBoss(id: 164, name: "Margit the Fell Omen", category: "Great Boss", detailedLocation: "Just past  Castleward Tunnel", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=163938"),
                        StaticBoss(id: 178, name: "Anastasia, Tarnished-Eater", category: "Invasion", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165194"),
                        StaticBoss(id: 180, name: "Bell Bearing Hunter", category: "Invasion", detailedLocation: "Knight Bernahl  at night", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165725"),
                        StaticBoss(id: 177, name: "Bloody Finger Nerijus", category: "Invasion", detailedLocation: "Between  Murkwater Catacombs  and  Murkwater Cave .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164492"),
                        StaticBoss(id: 203, name: "Old Knight Istvan", category: "Invasion", detailedLocation: "Underneath the Divine Bridge. Trigger by invading his world as part of Patches' Quest.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168977"),
                        StaticBoss(id: 179, name: "Recusant Henricus", category: "Invasion", detailedLocation: "Hammer Talisman", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165607")
                       ]),
        
        StaticLocation(name: "Liurnia",
                       goldenSeedCount: 5,
                       sacredTearsCount: 2,
                       crystalTearsCount: 7,
                       dragonHeartsCount: 5,
                       bosses: [
                        StaticBoss(id: 40, name: "Magma Wyrm Makar", category: "Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166245"),
                        StaticBoss(id: 50, name: "Adan, Thief of Fire", category: "Boss", detailedLocation: "Flame of the Fell God", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166505"),
                        StaticBoss(id: 64, name: "Alabaster Lord", category: "Boss", detailedLocation: "Royal Grave EvergoalMeteorite", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166766"),
                        StaticBoss(id: 46, name: "Black Knife Assassin", category: "Boss", detailedLocation: "Hidden boss in  Black Knife Catacombs  - Behind an illusionary wall at the end of the hallway next to the drop to the boss room door switch (?)", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166482"),
                        StaticBoss(id: 149, name: "Bloodhound Knight", category: "Boss", detailedLocation: "At the end of Lakeside Crystal Cave, after lowering down the pit.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168523"),
                        StaticBoss(id: 78, name: "Bols, Carian Knight", category: "Boss", detailedLocation: "Cuckoo's Evergaol", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167325"),
                        StaticBoss(id: 47, name: "Cemetery Shade (Black Knife Catacombs)", category: "Boss", detailedLocation: "Black Knife CatacombsTwinsage Sorcerer Ashes", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166484"),
                        StaticBoss(id: 42, name: "Cleanrot Knight", category: "Boss", detailedLocation: "Stillwater CaveWinged Sword Insignia", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166386"),
                        StaticBoss(id: 41, name: "Crystalian (Ringblade)", category: "Boss", detailedLocation: "Raya Lucaria Crystal Tunnel", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166381"),
                        StaticBoss(id: 49, name: "Death Rite Bird", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166501"),
                        StaticBoss(id: 28, name: "Deathbird (Liurna Lake)", category: "Boss", detailedLocation: "Only found at nightRed Feathered Branch Sword", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165597"),
                        StaticBoss(id: 143, name: "Erdtree Burial Watchdog", category: "Boss", detailedLocation: "At the end of Cliffbottom Catacombs.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168517"),
                        StaticBoss(id: 88, name: "Glintstone Dragon Adula", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167408"),
                        StaticBoss(id: 93, name: "Glintstone Dragon Adula (2nd Location)", category: "Boss", detailedLocation: "first location near Ranni's Rise , she will appear here.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167576"),
                        StaticBoss(id: 22, name: "Glintstone Dragon Smarag", category: "Boss", detailedLocation: "South-west of the  Crystalline Woods  Site of Grace, guarding the", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165267"),
                        StaticBoss(id: 125, name: "Godskin Noble", category: "Boss", detailedLocation: "On the bridge.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168277"),
                        StaticBoss(id: 37, name: "Night's Cavalry", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166181"),
                        StaticBoss(id: 56, name: "Night's Cavalry", category: "Boss", detailedLocation: "Forest near  East Raya Lucaria Gate Site of Grace . Only appears at night.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166645"),
                        StaticBoss(id: 43, name: "Omenkiller", category: "Boss", detailedLocation: "At the end of the path over the stone bridge through the Village of the Albinaurics, down in the caves, not the cathedral above it (?)", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166426"),
                        StaticBoss(id: 29, name: "Red Wolf of Ragadon", category: "Boss", detailedLocation: "Debate Hall", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165697"),
                        StaticBoss(id: 65, name: "Royal Revenant", category: "Boss", detailedLocation: "Kingsrealm Ruins  - Underground", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166772"),
                        StaticBoss(id: 44, name: "Spear Crystalian & Staff Crystalian", category: "Boss", detailedLocation: "Academy Crystal CaveCrystal Release", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166455"),
                        StaticBoss(id: 62, name: "Spirit Summoner Snail", category: "Boss", detailedLocation: "Road's End CatacombsGlintstone Sorcerer Ashes", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166749"),
                        StaticBoss(id: 54, name: "Tibia Mariner", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166619"),
                        StaticBoss(id: 158, name: "Rennala, Queen of the Full Moon", category: "Demigod", detailedLocation: "Raya Lucaria Academy", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164430"),
                        StaticBoss(id: 167, name: "Erdtree Avatar", category: "Great Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165594"),
                        StaticBoss(id: 168, name: "Erdtree Avatar", category: "Great Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165595"),
                        StaticBoss(id: 166, name: "Royal Knight Loretta", category: "Great Boss", detailedLocation: "Caria Manor", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165490"),
                        StaticBoss(id: 181, name: "Bell Bearing Hunter", category: "Invasion", detailedLocation: "Church of Vows  - Rest at night until  Miriel  disappears.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165744"),
                        StaticBoss(id: 186, name: "Bloody Finger Assassin", category: "Invasion", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166731"),
                        StaticBoss(id: 187, name: "Edgar The Revenger", category: "Invasion", detailedLocation: "Revenger's Shack . Rest at the Site of Grace to trigger the ivasion.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166811"),
                        StaticBoss(id: 188, name: "Festering Fingerprint Vyke", category: "Invasion", detailedLocation: "Church of Inhibition  - After completing the 4th part of  Hyetta's  quest (?)", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167188"),
                        StaticBoss(id: 202, name: "Great Horned Tragoth", category: "Invasion", detailedLocation: "Ruin-Strewn Precipice Overlook . Triggered by invading his world through the sigil.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168974"),
                        StaticBoss(id: 183, name: "Moongrum, Carian Knight", category: "Invasion", detailedLocation: "Just before the lift to  Raya Lucaria Grand Library .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165870"),
                        StaticBoss(id: 190, name: "Preceptor Miriam", category: "Invasion", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167680")
                       ]),
        
        StaticLocation(name: "Mountaintops of the Giants",
                       goldenSeedCount: 6,
                       sacredTearsCount: 2,
                       crystalTearsCount: 5,
                       dragonHeartsCount: 2,
                       bosses: [
                        StaticBoss(id: 134, name: "2x Night's Cavalry", category: "Boss", detailedLocation: "Guarding the wagon in the Snowfields", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168493"),
                        StaticBoss(id: 81, name: "Ancient Hero of Zamor", category: "Boss", detailedLocation: "Giant-Conquering Hero's Grave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167371"),
                        StaticBoss(id: 123, name: "Astel, Stars of Darkness", category: "Boss", detailedLocation: "Final Boss(es) of the  Abandoned Cave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168224"),
                        StaticBoss(id: 114, name: "Black Blade Kindred", category: "Boss", detailedLocation: "Base of the  Grand Lift of Rold", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168016"),
                        StaticBoss(id: 156, name: "Cheif Guardian Arghanthy", category: "Boss", detailedLocation: "[Guardian's Garrison] Ramparts.One-Eyed Shield", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=169140"),
                        StaticBoss(id: 74, name: "Commander Niall", category: "Boss", detailedLocation: "Castle Sol", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167290"),
                        StaticBoss(id: 113, name: "Death Rite Bird", category: "Boss", detailedLocation: "On the cliffside, north of  Shack of the Lofty", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168010"),
                        StaticBoss(id: 146, name: "Death Rite Bird", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168520"),
                        StaticBoss(id: 68, name: "Erdtree Avatar", category: "Boss", detailedLocation: "Base of the Minor Erdtree.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167138"),
                        StaticBoss(id: 147, name: "Erdtree Guardian", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168521"),
                        StaticBoss(id: 82, name: "Fire Giant", category: "Boss", detailedLocation: "By  Fire Giant  site of grace.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167375"),
                        StaticBoss(id: 121, name: "Great Wyrm Theodorix", category: "Boss", detailedLocation: "3x Dragon Heart", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168186"),
                        StaticBoss(id: 124, name: "Loretta, Knight of the Haligtree", category: "Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168228"),
                        StaticBoss(id: 103, name: "Malenia, Blade of Miquella", category: "Boss", detailedLocation: "Guarding the door to  Sainted Hero's Grave", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167678"),
                        StaticBoss(id: 151, name: "Misbegotten Crusader", category: "Boss", detailedLocation: "Cave of the Forlorn", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168661"),
                        StaticBoss(id: 129, name: "Putrid Grave Warden Duelist", category: "Boss", detailedLocation: "Consecrated Snowfield Catacombs", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168389"),
                        StaticBoss(id: 55, name: "Tibia Mariner", category: "Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166631"),
                        StaticBoss(id: 101, name: "Ulcerated Tree Spirit", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167668"),
                        StaticBoss(id: 128, name: "Vyke, Knight of the Roundtable", category: "Boss", detailedLocation: "Lord Contender's Evergoal", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168377"),
                        StaticBoss(id: 169, name: "Borealis The Freezing Fog", category: "Great Boss", detailedLocation: "??", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165642"),
                        StaticBoss(id: 182, name: "Bloody Finger Okina", category: "Invasion", detailedLocation: "Church of Repose", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165749"),
                        StaticBoss(id: 196, name: "Juno Hoslow, Knight of Blood", category: "Invasion", detailedLocation: "Near  Shack of the Lofty .", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168540"),
                        StaticBoss(id: 191, name: "Sanguine Noble", category: "Invasion", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168005"),
                        StaticBoss(id: 199, name: "Tarnished Eater", category: "Invasion", detailedLocation: "Upstairs in  Volcano Manor", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168843")
                       ]),
        
        StaticLocation(name: "Roundtable Hold",
                       goldenSeedCount: 0,
                       sacredTearsCount: 0,
                       crystalTearsCount: 0,
                       dragonHeartsCount: 0,
                       bosses: [ StaticBoss(id: 189, name: "Ensha of the Royal Remains", category: "Invasion", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167506"),
                                 StaticBoss(id: 200, name: "Mad Tongue Alberich", category: "Invasion", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168844")]),
        
        StaticLocation(name: "Siofra River",
                       goldenSeedCount: 2,
                       sacredTearsCount: 0,
                       crystalTearsCount: 0,
                       dragonHeartsCount: 0,
                       bosses: [
                        StaticBoss(id: 104, name: "Ancestor Spirit", category: "Boss", detailedLocation: "Hallowhorn Grounds", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167775"),
                        StaticBoss(id: 110, name: "Dragonkin Soldier", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167928"),
                        StaticBoss(id: 126, name: "Mimic Tear", category: "Boss", detailedLocation: "Nokron, Eternal City", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168280"),
                        StaticBoss(id: 130, name: "Valiant Gargoyle & Valiant Gargoyle (Twinblade)", category: "Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168404"),
                        StaticBoss(id: 163, name: "Mohg, Lord of Blood", category: "Demigod", detailedLocation: "At the top of the mausoleum in Mohgwyn Palace.", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168412"),
                        StaticBoss(id: 174, name: "Regal Ancestor Spirit", category: "Great Boss", detailedLocation: "", locationURL: "https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167929")
                       ])
    ]
}
